In [1]:
import numpy as np

In [2]:
#Cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [4]:
#Cria o array com um tipo específico
#Cria o array com float de 64 bits
mfloat = np.array([1,2,3], dtype = np.float64)
print(mfloat)
print(type(mfloat))
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [5]:
#Mudar o tipo de array
#Podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.99999])
print(mtnew)
#quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4      3.6     -5.1      9.42     4.99999]
[ 1  3 -5  9  4]


In [6]:
# podemos fazer o inverso também
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [7]:
# mais de uma dimensão
# cria uma matriz bidimensional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [8]:
# Criar arrays vazios típificados
# empty significa que não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("---------")
# cria uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("---------")
#com valores igual a um
um = np.ones([5,7])
print(um)
print("---------")
# cria matriz quadrada com diagonal princípal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
---------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
---------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
# valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print("---------")
# valores aleatórios distr. normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print("---------")
# valores aleatórios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.66633295 0.03153027 0.3602755  0.30347748 0.37651055]
---------
[ 0.22338526 -0.49217881 -1.01386173 -0.8021146   0.34669637]
---------
[[5.59605679 7.16295089 3.479879   2.77064596]
 [0.10580593 5.71277814 3.13217962 8.95188975]
 [9.8061724  7.76586598 9.41488267 8.56263604]]


In [11]:
# outra forma de gerar aleatórios
#uso de semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

#gerar inteiros
ale6 = gnr.integers(10, size=(3, 4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [14]:
# unique remove repetições
j = np.array([11,12,13,14,15,16,17,12,13,11,18,19,20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [16]:
# funções específicos
# cria a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
# Mostra a matriz k
print(k)
# Mostra um elemento específico da matriz K
print(k[0][1])
# Mostra o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [17]:
# fubções Matemátcias
# Mostra o maior valor da matriz k
print(k.max())
# Mostra o menor valor da matriz k
print(k.min())
# Mostra a soma dos valores da matriz k
print((k.sum()))
# Mostra o valor da média dos valores da matriz k
print(k.mean())
# Mostra o valor do desvio padrão (standará deviotion) dos valores da matriz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [18]:
# funções universais, aplicadas a todos os elementos
# Mostra o valor da raiz quadrada de todos elementos
k1 = np.array([1,4,9,16,25,36])
print(np.sqrt(k1))
# Mostra o valor do exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [19]:
# entração de elementos
m = np.array([1,2,3,4,5,6])
# Mostra o elemento da posção 2
print(m[1])
print("---------")
# Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print("---------")
# Mostra o array criado a partir da segunda posição
# até todo o restante do array
print(m[1:])
print("---------")
# Mostra o array criado a partir do antepenúltima
# posição até o final
print(m[-3:])

2
---------
[1 2]
---------
[2 3 4 5 6]
---------
[4 5 6]


In [20]:
# Extração de linhas e colunas

l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print("---------")
# primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print("---------")
# segunda linha
l_linha_2 = l[1, :]
print(l_linha_2)
print("---------")
# terceira linha
l_linha_3 = l[2, :]
print(l_linha_3)
print("---------")
# todas as linhas, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)
print("---------")
# todas as linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)


[[4 5]
 [6 1]
 [7 4]]
---------
[4 5]
---------
[6 1]
---------
[7 4]
---------
[4 6 7]
---------
[5 1 4]


In [21]:
# adição e multiplicação de matrizes
n = np.array([[1,2],[3,4]])
o = np.array([[1,1],[1,1]])
res1 = n+o
print(res1)
print("---------")
res2 = n*o
print(res2)
print("---------")
p = np.array([[1,2],[3,4],[5,6]])
q = np.array([[2,1]])
print(p+q)


[[2 3]
 [4 5]]
---------
[[1 2]
 [3 4]]
---------
[[3 3]
 [5 5]
 [7 7]]


In [22]:
# transposição, rearranjo um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))
# mostra a matrizes transposta entre linha e coluna
print(f)
print("---------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
---------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [23]:
# outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3,5))
print(r)
print("---------")
# rearranjo um conjuno de 15 elementos
# mostra a maatrizes transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
---------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [24]:
# expressções lógicos
# usando where
# crainado matriz com valores aleatórios positivos e negativos
v = np.random.randn(4,4)
print(v)
# craindo matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
# criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[ 1.56306436  0.40436601  2.04363839 -2.04998957]
 [-0.29421313  1.62880292 -0.37433866  1.63845352]
 [-0.00358246 -0.38955927 -1.62585264 -0.66853696]
 [ 0.19627864  1.36013285  0.51479813  1.37563656]]
[[ True  True  True False]
 [False  True False  True]
 [False False False False]
 [ True  True  True  True]]
[[ 1  1  1 -1]
 [-1  1 -1  1]
 [-1 -1 -1 -1]
 [ 1  1  1  1]]
